[theme]
base = "dark"
primaryColor = "#1BCACA"
backgroundColor = "#07111A"
secondaryBackgroundColor = "#0F1E2A"
textColor = "#E2E2E2"
font = "sans serif"

[server]
headless = true
fileWatcherType = "auto"
